version: '3.7'

services:
  tomcat:
    image: tomcat:latest
    volumes:
      - /vagrant/tomcat/logs/:/usr/local/tomcat/logs
    ports:
      - 8080:8080
  nginx:
    image: nginx:latest
    # build:
    #   context: .
    #   dockerfile: /vagrant/DockerfileNginx
    #   args:
    #     CONFIG_DIR: /vagrant/nginx
    volumes:
      - /vagrant/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    command: [nginx, '-g', 'daemon off;']
      