version: '3.7'

services:
  tomcat:
    image: tomcat:latest
    volumes:
      - /vagrant/tomcat/logs/:/usr/local/tomcat/logs
      - /vagrant/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    ports:
      - 8080:8080
