version: '3.7'

services:
  tomcat:
    image: tomcat:latest
    volumes:
      - /vagrant/tomcat/logs/:/usr/local/tomcat/logs
    ports:
      - 8080:8080
  nginx:
    image: nginx:latest
    volumes:
      - /vagrant/nginx/conf.d/default.conf.template:/etc/nginx/conf.d/default.conf.template
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
      